name = "Pretalx"
uuid = "15f9c654-ce21-11e9-324d-3991268b094d"
authors = ["Lyndon White"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
